export const gepaBirchRun = {
  "run": "20260622-232604-birch-minimal-workspace-vlm5",
  "source": "/home/shaun/source/simple-gepa/runs/birch/20260622-232604-birch-minimal-workspace-vlm5",
  "items": [
    {
      "id": "candidate-0001",
      "iteration": 1,
      "image": "gepa-birch/candidate-0001-deep.png",
      "score": 0.45,
      "generation": 1.0,
      "checker": 0.0,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 34,
      "recipeLines": 4,
      "toolCalls": 20,
      "turns": 21,
      "totalTokens": 442668,
      "checkerFailures": 6,
      "checkerWarnings": 5,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0002",
      "iteration": 2,
      "image": "gepa-birch/candidate-0002-deep.png",
      "score": 0.45,
      "generation": 1.0,
      "checker": 0.0,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 34,
      "recipeLines": 4,
      "toolCalls": 11,
      "turns": 12,
      "totalTokens": 117340,
      "checkerFailures": 7,
      "checkerWarnings": 4,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0003",
      "iteration": 3,
      "image": "gepa-birch/candidate-0003-deep.png",
      "score": 0.3,
      "generation": 1.0,
      "checker": 0.0,
      "hygiene": 0.0,
      "skillLengthScore": 1.0,
      "skillLines": 234,
      "recipeLines": 4,
      "toolCalls": 9,
      "turns": 10,
      "totalTokens": 62633,
      "checkerFailures": 5,
      "checkerWarnings": 5,
      "missingCssArtifacts": 1,
      "scoreCap": 0.55,
      "hasOutput": true
    },
    {
      "id": "candidate-0004",
      "iteration": 4,
      "image": "gepa-birch/candidate-0004-deep.png",
      "score": 0.45,
      "generation": 1.0,
      "checker": 0.0,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 34,
      "recipeLines": 4,
      "toolCalls": 10,
      "turns": 11,
      "totalTokens": 51277,
      "checkerFailures": 5,
      "checkerWarnings": 6,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0005",
      "iteration": 5,
      "image": "gepa-birch/candidate-0005-deep.png",
      "score": 0.714,
      "generation": 1.0,
      "checker": 0.48,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 34,
      "recipeLines": 71,
      "toolCalls": 63,
      "turns": 64,
      "totalTokens": 1201203,
      "checkerFailures": 2,
      "checkerWarnings": 4,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0006",
      "iteration": 6,
      "image": "gepa-birch/candidate-0006-deep.png",
      "score": 0.6205,
      "generation": 1.0,
      "checker": 0.31,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 34,
      "recipeLines": 71,
      "toolCalls": 14,
      "turns": 15,
      "totalTokens": 94209,
      "checkerFailures": 3,
      "checkerWarnings": 3,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0007",
      "iteration": 7,
      "image": "gepa-birch/candidate-0007-deep.png",
      "score": 0.45,
      "generation": 1.0,
      "checker": 0.0,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 34,
      "recipeLines": 71,
      "toolCalls": 40,
      "turns": 41,
      "totalTokens": 523068,
      "checkerFailures": 5,
      "checkerWarnings": 4,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0008",
      "iteration": 8,
      "image": "gepa-birch/candidate-0008-deep.png",
      "score": 0.9505,
      "generation": 1.0,
      "checker": 0.91,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 170,
      "recipeLines": 71,
      "toolCalls": 27,
      "turns": 28,
      "totalTokens": 232992,
      "checkerFailures": 0,
      "checkerWarnings": 3,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0009",
      "iteration": 9,
      "image": "gepa-birch/candidate-0009-deep.png",
      "score": 0.7635,
      "generation": 1.0,
      "checker": 0.57,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 170,
      "recipeLines": 71,
      "toolCalls": 19,
      "turns": 20,
      "totalTokens": 145431,
      "checkerFailures": 2,
      "checkerWarnings": 1,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0010",
      "iteration": 10,
      "image": "gepa-birch/candidate-0010-deep.png",
      "score": 0.747,
      "generation": 1.0,
      "checker": 0.54,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 170,
      "recipeLines": 71,
      "toolCalls": 15,
      "turns": 16,
      "totalTokens": 118781,
      "checkerFailures": 2,
      "checkerWarnings": 2,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0011",
      "iteration": 11,
      "image": "gepa-birch/candidate-0011-deep.png",
      "score": 0.9835,
      "generation": 1.0,
      "checker": 0.97,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 170,
      "recipeLines": 115,
      "toolCalls": 12,
      "turns": 13,
      "totalTokens": 87656,
      "checkerFailures": 0,
      "checkerWarnings": 1,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    },
    {
      "id": "candidate-0012",
      "iteration": 12,
      "image": "gepa-birch/candidate-0012-deep.png",
      "score": 0.9505,
      "generation": 1.0,
      "checker": 0.91,
      "hygiene": 1.0,
      "skillLengthScore": 1.0,
      "skillLines": 170,
      "recipeLines": 115,
      "toolCalls": 14,
      "turns": 15,
      "totalTokens": 105125,
      "checkerFailures": 0,
      "checkerWarnings": 3,
      "missingCssArtifacts": 0,
      "scoreCap": 1.0,
      "hasOutput": true
    }
  ]
} as const
